apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: career-loop-ingress
  namespace: career-loop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true" # Enable regex for path matching
spec:
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific # Use ImplementationSpecific for regex paths
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - path: /()(.*)
            pathType: ImplementationSpecific # Use ImplementationSpecific for regex paths
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
